name = "lapce-tex"
version = "0.0.0"
author = "Jonas Kjellerup"
display-name = "TeX (TexLab)"
description = "A TeX plugin for lapce using texlab LSP"
wasm = "bin/lapce-tex.wasm"

[activation]
language = ["latex"]
workspace-contains = [
  "*/*.tex",
  "*/*.sty",
  "*/*.cls",
  "*/*.bib",
]

[config."volt.serverPath"]
default = "texlab"
description = "Path to texlab executable"

[config."texlab.build.executable"]
default = "latexmk"
description = "The executable texlab will use to build the project"

[config."texlab.build.args"]
default = []
description = "Arguments to pass to build tool."

[config."texlab.build.onSave"]
default = false
description = "Whether the project should be built on save."

[config."texlab.auxDirectory"]
default = "."
description = "The directory that build artifacts will be stored in."

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
